### PR TITLE
FIXED ALL OF ANAND'S STUPID DERPS IN XDA TEMPLATE

### PR DESCRIPTION
**Pull request by vrnsoma**
DON'T DO STUPID DERPS

### CODE REVIEW

**Comment by Anandnv** [comment]
@vrnsoma

**Comment by vrnsoma** [comment]
ya wat

**Comment by kishpatel1998** [comment]
@vrnsoma 😂😂😂😂

**Comment by Anandnv** [comment]
tenor

**Comment by Anandnv** [comment]
@vrnsoma come and check again you cunt

**Review by Anandnv — APPROVED** [review]

**Comment by ghost** [comment]
Do not merge. There is no derp

**Comment by vrnsoma** [comment]
STFU @anupritaisno1 @Anandnv when ur stuck in class, and you have a chromebook, but no telegram XD...life sucks

**Comment by Anandnv** [comment]
@vrnsoma I iz poor .. Not reech like u

**Comment by ghost** [comment]
Chromebooks are shit. Not as much as you

**Comment by vrnsoma** [comment]
It would be nice if I get direct write permissions...you know ;)

**Comment by vrnsoma** [comment]
Whats up with your lappy

**Comment by Anandnv** [comment]
Shhht de fek app

**Pull request merged**
